version: '3.3'
services:
    database:
        image: 'postgres'
        container_name: 'diploma-postgres'
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres